name: gost
base: core20
version: '0.0.1'
summary: A simple security tunnel written in golang
description: |
  Project: https://github.com/AikoCute-Offical/gost
  Wiki: Coming Soon
icon: gost.png
website: Coming Soon
license: MIT


confinement: strict
grade: stable

parts:
  gost:
    plugin: go
    go-channel: latest/stable
    source: https://github.com/ginuerzh/gost
    source-subdir: cmd/gost
    source-type: git
    source-tag: v0.0.1
    build-packages:
    - gcc

apps:
  gost:
    command: bin/gost
    plugs: 
    - home
    - network
    - network-bind

